### ISSUE TITLE
Normalized RTFCRE stroke is inconsistent with Plover for `#H-B`

### ISSUE THREAD

**Issue by user202729** [benoit-pierre/plover_stroke#1]
`#H-B` doesn't work in Plover, only `4-B` does.

However this plugin reports the normalized form of `4-B` as `#H-B`.

(it could also be a Plover bug for not recognizing `#H-B`; however making the normalized RTFCRE form different between Plover and this library is not a good idea)

**Comment by benoit-pierre** [comment]
Should be fixed in 1.0.0.
